# Feel free to disable non-critical HA parts during devel by commenting lines out
# Generated in hadk by executing: rpm/dhd/helpers/add_new_device.sh

Description: Pattern with packages for mido configurations
Name: jolla-configuration-mido
Requires:
- patterns-sailfish-device-configuration-mido

Summary: Jolla Configuration mido

